server:
  port: 8081
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka-server-cadalso.herokuapp.com/eureka
#      defaultZone: http://localhost:8761/eureka
    
#As configurações do OAuth2 estão no servidor de configuração.
     