server:
  port: 8081
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://eureka-server-cadalso.herokuapp.com/eureka
#      defaultZone: http://localhost:8761/eureka
    
security:
  oauth2:
   resource:
     user-info-uri: http://localhost:8088/user #A URL do servidor de autenticação que retorna os dados do usuário autenticado.
     